// auth

// layout

export const LAYOUT_UPDATE = "LAYOUT_UPDATE";

export const GET_ERRORS = 'GET_ERRORS'
export const SHOW_DATA_EDIT = 'SHOW_DATA_EDIT';

export const Auth = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GET_ERRORS: "GET_ERRORS",
  CHANGE_MODAL_STATUS: "CHANGE_MODAL_STATUS",
  RECOVERY_EMAIL_SENT: "RECOVERY_EMAIL_SENT",
  RECOVERY_EMAIL_NOT_SENT: "RECOVERY_EMAIL_NOT_SENT",
  CHANGE_PASSWORD_TRUE: "CHANGE_PASSWORD_TRUE",
  CHANGE_PASSWORD_FALSE: "CHANGE_PASSWORD_FALSE"
};

export const Notification = {
  CREATE_NOTIFICATION_SUCCESS: "CREATE_NOTIFICATION_SUCCESS",
  CREATE_NOTIFICATION_ERROR: "CREATE_NOTIFICATION_ERROR",
  GET_ALL_NOTIFICATION_SUCCESS: "GET_ALL_NOTIFICATION_SUCCESS",
  GET_ALL_NOTIFICATION_ERROR: "GET_ALL_NOTIFICATION_ERROR",
  GET_NOTIFICATION_SUCCESS: "GET_NOTIFICATION_SUCCESS",
  GET_NOTIFICATION_ERROR: "GET_NOTIFICATION_ERROR",
  DELETE_NOTIFICATION_SUCCESS: "DELETE_NOTIFICATION_SUCCESS",
  DELETE_NOTIFICATION_ERROR: "DELETE_NOTIFICATION_ERROR",
  UPDATE_NOTIFICATION_SUCCESS: "UPDATE_NOTIFICATION_SUCCESS",
  UPDATE_NOTIFICATION_ERROR: "UPDATE_NOTIFICATION_ERROR"
};
